In [10]:
import sys
import os
# Adiciona a raiz do projeto ao path para localizar 'src'
sys.path.append(os.path.abspath(os.path.join('..')))

from src.database.connection import get_engine
from src.components.transformersCasoNome import processar_usuarios_etl
import pandas as pd

engine = get_engine()
print("Conexão estabelecida!")

Conexão estabelecida!

In [11]:
query = "SELECT * FROM usuarios_temp_nomes_brasil"
df_bruto = pd.read_sql(query, engine)
print(f"{len(df_bruto)} registros extraídos.")
df_bruto.head()

6 registros extraídos.

   id               nome_completo  data_venda  valor
0   1                Ana da Silva  10/25/2025  150.5
1   2       Ewerton José da Silva  03/12/2026  200.0
2   3             Antônio Antunes  12/01/2025   75.0
3   4  Mário Mauro Moreira Mendes  04/15/2026  320.1
4   5                Eliele Braga  05/20/2026   50.0

# Estratégia A: Padrão de formulário (Primeiro nome isolado)

In [12]:
df_A = processar_usuarios_etl(df_bruto, estrategia='primeiro_termo')
display(df_A.head())

  primeiro_nome             sobrenome
0           ANA              da SILVA
1       EWERTON         JOSÉ da SILVA
2       ANTÔNIO               ANTUNES
3         MÁRIO  MAURO MOREIRA MENDES
4        ELIELE                 BRAGA

# Estratégia B: Padrão acadêmico (Último sobrenome isolado)

In [13]:
df_B = processar_usuarios_etl(df_bruto, estrategia='ultimo_sobrenome')
display(df_B.head())

         primeiro_nome sobrenome
0               ANA da     SILVA
1      EWERTON JOSÉ da     SILVA
2              ANTÔNIO   ANTUNES
3  MÁRIO MAURO MOREIRA    MENDES
4               ELIELE     BRAGA